[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mlops_eurosat"
version = "0.0.1"
description = "MLOps pipeline for land use classification on the EuroSAT dataset."
authors = [
  { name = "Cosima Fröhner", email = "c.froehner@campus.lmu.de" },
  { name = "Philip Studener", email = "p.studener@campus.lmu.de" },
  { name = "Michael Speckbacher", email = "mi.speckbacher@campus.lmu.de" },
]

keywords = ["machine learning", "MLOps"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
]
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
dev = {file = ['requirements_dev.txt']}

[tool.ruff]
line-length = 120
src = ["src"]

[tool.ruff.lint]
select = ["I", "N", "E", "W", ]

[tool.coverage.run]
omit = ["tests/*"]

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true

[[tool.mypy.overrides]]
module = ["sklearn.*", "google.cloud.*", "kfp.*", "google_cloud_pipeline_components.*", "onnxruntime"]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--cov=src/mlops_eurosat --cov-report=term-missing"

[[tool.mypy.overrides]]
module = ["wandb", "wandb.*", "google.cloud.*", "requests", "streamlit_folium"]
ignore_missing_imports = true
follow_imports = "skip"

[tool.ruff.lint.isort]
known-first-party = ["mlops_eurosat"]
