workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-32
  replicaCount: 1
  containerSpec:
    imageUri: europe-west3-docker.pkg.dev/mlops-eurosat-496913/mlops-eurosat/train:latest
    command:
    - bash
    - -c
    - "dvc pull && wandb agent --count COUNT_PLACEHOLDER SWEEP_ID_PLACEHOLDER"
    env:
    - name: WANDB_API_KEY
      value: REPLACE_WITH_YOUR_KEY
