site_name: mlops_eurosat
site_author: Cosima Fröhner, Philip Studener, Michael Speckbacher
site_description: MLOps pipeline for land use classification on the EuroSAT dataset
site_url: https://mlops-eurosat.github.io/MLOps-EuroSAT/
repo_url: https://github.com/mlops-eurosat/MLOps-EuroSAT
repo_name: mlops-eurosat/MLOps-EuroSAT
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.tracking

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false
            show_root_toc_entry: false
            heading_level: 4
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Python Module Reference: api.md
